### ISSUE TITLE
Blog Post: 2024-09-27

### ISSUE THREAD

**Issue by AugustDG** [TheNewtonCapstone/blog#16]
What should we talk about?

**Comment by AugustDG** [comment]
I suggest we do a piece on the complications of communication! @Shamiivan

**Comment by Shamiivan** [comment]
Agreed! 
Will get the outline going.

**Comment by AugustDG** [comment]
Did you have time to make an outline?

**Comment by Shamiivan** [comment]
Nope, I failed:/
